### ISSUE TITLE
Utilize o pacote de imagens ofertados pelo cliente, crie um sistema de cards publicitários com descrições na página inicial.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#40]
Utilize o pacote de imagens ofertados pelo cliente, crie um sistema de cards publicitários com descrições na página incial.

Referências:

- https://getbootstrap.com/docs/5.3/components/card/

**Comment by odavist** [comment]
![image](https://github.com/luc4sleite/goservice/assets/102368948/641de8d2-99d9-4682-a50e-63b71903df07)
![image](https://github.com/luc4sleite/goservice/assets/102368948/06c2d446-5268-49ee-a296-38716ae40818)
