### ISSUE TITLE
Crie um método para possibilitar a alteração de endereço do usuário.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#42]
Crie um novo repository para Endereço que permita manipular informações de endereço no banco de dados. Crie nele uma consulta personalizada para possibilite a alteração dos dados de endereço especificado pela identificação do usuário (e-mail ou id). Crie também o serviço para Endereço com método que integra essa alterar de dados.

**Comment by KSSIMIRO** [comment]
criação do método update para a alteração de endereço



![Image](https://github.com/luc4sleite/goservice/assets/136914180/9d1ca7bc-cf02-4480-a0a8-f6b1d4e0d54d)

 criação de uma Query que permita o Repository alterar o endereço



![Image](https://github.com/luc4sleite/goservice/assets/136914180/06bb87b5-ef15-40fb-96fd-052f5a76619a)

**Comment by KSSIMIRO** [comment]
Correção de bug no EnderecoRepository



![Image](https://github.com/luc4sleite/goservice/assets/136914180/a817e22a-5888-4239-9a99-d03e0f2ed778)

E alteração no EnderecoService para funcionar com a correção 



![Image](https://github.com/luc4sleite/goservice/assets/136914180/f0c46f5d-a47b-43b3-8b5d-16c8b921b328)
