### ISSUE TITLE
Construa e faça o mapeamento para a página de Termos e Condições e Politicas de Privacidade.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#52]
Crie uma página de Termos e Condições e Politicas de Privacidade. E faça o mapeamento adequadamente da página.

**Comment by KSSIMIRO** [comment]
Criação das páginas de termos de uso e politicas de privacidade:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/e6ff16fb-6acc-4213-809f-ab928aafc366)

Mapeamento das duas página no AuthController:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/a374b464-ebad-45b1-8eaa-c0016301dbfb)

Alteração na página de cadastro com um link para termos de uso e políticas de privacidade



![Image](https://github.com/luc4sleite/goservice/assets/136914180/94d46ee6-2788-464b-8410-72ee94b98334)



![Image](https://github.com/luc4sleite/goservice/assets/136914180/610f7d23-d110-4767-9532-143affde33af)
