### ISSUE TITLE
Crie um novo fragmento para rodapé aplicado em todas as páginas com exceção do cadastro e login.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#53]
Utilizando os modelos de prontos do bootstrap, crie um novo rodapé com direitos autorais e links públicos e para a página de termos e condições e politicas de privacidade e FAQ.

Referências:

- https://getbootstrap.com/docs/5.3/examples/footers/

**Comment by KSSIMIRO** [comment]
Criação do fragmento footer:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/b06b767b-46eb-49a4-86a3-7b19ca265201)



adicionando o refragments do footer em todas as páginas HTML exceto em login e cadastro:

- ![Image](https://github.com/luc4sleite/goservice/assets/136914180/ce2e1114-1907-4949-90cf-017b76735dea)
