### ISSUE TITLE
Utilize o recurso de tooptip para aplicar dicas nos botões do site.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#54]
Para uma melhor experiência e acessibilidade aplique dicas em todos os botões e imagens clicáveis da aplicação.

Referências:

- https://getbootstrap.com/docs/5.3/components/tooltips/

**Comment by KSSIMIRO** [comment]
Add um constante no JS para possibilitar a aparição da mensagem:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/be8aabd9-e117-4abe-aa86-47831a842cb8)

E add o código do bootstrap no botão para ele exibir a mensagem.



![Image](https://github.com/luc4sleite/goservice/assets/136914180/cc4a0027-af7c-49e0-8018-5aea23966d3f)
