### ISSUE TITLE
Verificação da disponibilidade de agendamento no horário definido.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#71]
No momento de agendamento do cliente, crie uma verificação referente a disponibilidade do Prestador no horário definido. Crie uma exceção personalizada para lançar no caso de conflito de horário. Mostre uma mensagem de erro quando ocorrer este conflito.

**Comment by PedroRossetto** [comment]
![image](https://github.com/luc4sleite/goservice/assets/137007809/2a2d434a-be87-423c-9427-5c326dce5459)
