### ISSUE TITLE
Verificação da data de agendamento.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#73]
A data do agendamento é flexível ao cliente para que ele posso escolher. Porém ele pode escolher uma data que já passou, causando inconsistência nos dados da aplicação. Para evitar isso, crie uma validação simples antes de salvar o agendamento, o qual verifica se a data e hora é superior ao momento que ele efetuou o agendamento, lançando e tratando uma exceção personalizada para isso. Além disso, crie um script JS no template para bloquear a seleção de data anteriores, garantindo uma melhor usabilidade.

**Comment by KSSIMIRO** [comment]
Alteração no método de agendamento de serviço no ClienteController



![Image](https://github.com/luc4sleite/goservice/assets/136914180/f6fcae5b-68a7-44e6-8fa8-78ba1f5787f2)

Bloqueando a seleção de datas que já passaram no JS



![Image](https://github.com/luc4sleite/goservice/assets/136914180/41ee2848-33d4-450f-8c9f-41a934459f47)


criação de uma exceção especifica



![Image](https://github.com/luc4sleite/goservice/assets/136914180/b09c213d-2fea-47f8-9011-4d7d058f74d1)
