### ISSUE TITLE
Permite que o Administrador também altere os seus dados cadastrais.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#75]
O Administrador não tem possibilidade de mudar seu e-mail, nome, etc. Crie uma página que permite que o administrador altere os dados cadastrais bem como sua foto de perfil.

**Comment by KSSIMIRO** [comment]
Criação da pagina do formulário para trocar os dados:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/d2e53875-1faa-4188-a1a7-8ae1a18e97b9)

Mapeamento da pagina e captura dos dados para serem alterados no AdministradorController:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/cbdf2ae6-b0f8-4a40-9ffc-5a9c0c4f9087)

Criação do serviço e repositório do administrador:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/b72ac375-7a7a-4661-836b-aba6cdfeec2b)
