### ISSUE TITLE
Utilize anotações do Lombok para evitar a utilização explicita dos métodos getters e setters.

### ISSUE THREAD

**Issue by luc4sleite** [luc4sleite/goservice#89]
Lombok é uma biblioteca Java focada em produtividade e redução de código. Para melhorar a legibilidade das classes de domínio da aplicação adicione as anotações de Lombok para evitar a escrita dos métodos Getters e Setters. Remova todos os métodos escritos anteriormente.

Referências:

- https://www.baeldung.com/intro-to-project-lombok

**Comment by KSSIMIRO** [comment]
add a dependência do Lombok no pom.xml: 


![Image](https://github.com/luc4sleite/goservice/assets/136914180/1c4dd4b6-5734-40f6-9735-79569874b30c)


Colocando a notação do Lombok nos Domains(alteração feita em todos os domains, menos em Administrador):


![Image](https://github.com/luc4sleite/goservice/assets/136914180/a6081f5a-b218-40b9-8198-49923dfc7797)

Em alguns deu para colocar a notação que substitui o construtor vazio.



![Image](https://github.com/luc4sleite/goservice/assets/136914180/fc36976f-ed77-4fb1-9c53-1f8c078f6902)

**Comment by KSSIMIRO** [comment]
Add os métodos @Getter e @Setter no domain mensagem que foi adicionado após a conclusão da task:



![Image](https://github.com/luc4sleite/goservice/assets/136914180/05cc6fd3-5140-4093-8eb3-d4a2f7232c5a)
